### ISSUE TITLE
Push constant size limit exceeded

### ISSUE THREAD

**Issue by simplerr** [simplerr/UtopianEngine#139]
Error: 1972820933:Validation Error: [ VUID-vkCmdPushConstants-size-00371 ] Object 0: handle = 0x2916c0a1740, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7596dbc5 | vkCmdPushConstants(): offset (0) and size (192) that exceeds this device's maxPushConstantSize of 128. The Vulkan spec states: size must be less than or equal to VkPhysicalDeviceLimits::maxPushConstantsSize minus offset (https://vulkan.lunarg.com/doc/view/1.3.216.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdPushConstants-size-00371)
Object[0] - Type: VkDevice, Value: 000002916C0A1740, Name: Unnamed

**Comment by haikarainen** [comment]
Possible baddie, as it has > 128 bytes (192 to be exact) of push constants, and from what I can tell the only place this codebase sets the pc range is from shader reflection. This seems to be the only shader that overflows the Vulkan min. limit.

https://github.com/simplerr/UtopianEngine/blob/4b5540e8732de138f3272d5abd3d1963c9793439/data/shaders/atmosphere/atmosphere.vert

**Comment by simplerr** [comment]
Thanks for identifying which shader that exceeded the limit, a fix for it has been pushed :)
